server:
  port: 9000
  contextPath:
path:
  mp3: E:/CloudMusic
spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:~/cdboo
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: /sql/schema-h2.sql
    #data: /sql/data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/, file:${path.mp3}
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
  file: logs/cdboo.log

#系统配置
url:
  cdboo:
    server:
      ip: http://139.129.240.92:8080/cdboo
      checkUser: /cdboo-service/check-user
      getUserData: /cdboo-service/get-data
    client:
      ip: http://127.0.0.1:9000
      index: