spring:
  datasource:
    platform: h2
    url: jdbc:h2:~/cdboo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #schema: /sql/schema-h2.sql
    #data: /sql/data-h2.sql
  jpa:
    hibernate:
      ddl-auto: update