server:
    port: 9000
    contextPath:
spring:
  datasource:
    platform: h2
    url: jdbc:h2:~/cdboo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: /sql/schema-h2.sql
    #data: /sql/data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file: logs/cdboo.log